#!/bin/bash
#
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running.
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

startOnce() {
  if [ -z "$(pgrep $1)" ]; then
    $* &
  fi
}

# Tray: Empathy chat client (-h: startOnce hidden, -n: don't connect on launch)
startOnce empathy -h -n
# Tray: Remmina remote desktop connection client (-i: start hidden)
startOnce remmina -i
# Tray: Network manager, so we don't have to configure wifi at the command line.
startOnce nm-applet --sm-disable
# Tray: Applet for managing print jobs from the tray.
startOnce system-config-printer-applet
# Launcher: Use synapse as our app launcher. (-s: don't display until requested)
startOnce synapse -s

# Apps
if [ "$(ps aux | grep [g]oogle.chrome | wc -l)" -eq 0 ]; then # Chrome runs with a different process name than you start it, so I can't use startOnce.
  google-chrome &
fi
startOnce pidgin
startOnce thunderbird
startOnce gnome-terminal -x tmux attach -d
