# Generated by iptables-save v1.4.18 on Thu Dec 19 17:14:25 2013
*filter
:INPUT DROP [19:4279]
-A INPUT -p tcp --dport ssh -j ACCEPT
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [5:2934]
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
COMMIT
# Completed on Thu Dec 19 17:14:25 2013
